#define NPROC        64  // maximum number of processes (最大进程数)
#define NCPU          8  // maximum number of CPUs (最大中央处理器数量)
#define NOFILE       16  // open files per process (每个进程打开的文件数)
#define NFILE       100  // open files per system (系统打开的文件总数)
#define NINODE       50  // maximum number of active i-nodes (活动i节点最大数量)
#define NDEV         10  // maximum major device number (最大主设备号)
#define ROOTDEV       1  // device number of file system root disk (文件系统根磁盘设备号)
#define MAXARG       32  // max exec arguments (最大执行参数数量)
#define MAXOPBLOCKS  10  // max # of blocks any FS op writes (任何文件系统操作写入的最大块数，OP=Operation)
#define LOGBLOCKS    (MAXOPBLOCKS*3)  // max data blocks in on-disk log (磁盘日志中的最大数据块数)
#define NBUF         (MAXOPBLOCKS*3)  // size of disk block cache (磁盘块缓存大小)
#define FSSIZE       2000  // size of file system in blocks (文件系统块大小)
#define MAXPATH      128   // maximum file path name (最大文件路径名长度)
#define USERSTACK    1     // user stack pages (用户栈页数)

